app/package.json, app/yarn.lock
This will fix the issue with the modal not rendering
=> chore: update sso-react package

app/server/schema.graphql, app/server/schema.json, schema/deploy/tables/project_manager.sql, schema/revert/tables/project_manager.sql, schema/sqitch.plan, schema/verify/tables/project_manager.sql
Creating a project manager table so we can track assignment of users (managers) to a project
=> Task: create project manager table

.secrets.baseline, app/server/schema.graphql, app/server/schema.json, schema/deploy/tables/funding_stream.sql, schema/deploy/tables/project.sql, schema/revert/tables/funding_stream.sql, schema/sqitch.plan, schema/verify/tables/funding_stream.sql
- funding stream table added with id, name, description
- project table foreign key to funding stream added (funding_stream_id)
=> feat: funding stream table added

app/mutations/attachment/createAttachment.ts, app/pages/admin/attachments.tsx
reloads the attachments view when the upload mutation completes to refresh the local store
=> fix: reload on mutation complete

.secrets.baseline, app/components/Form/SavingIndicator.tsx, app/jest.config.ts, app/lib/relay/client.ts, app/lib/relay/debounceMutationMiddleware.ts, app/mutations/useDebouncedMutation.ts, app/package.json, app/pages/cif/create-project.tsx, app/server/schema.graphql, app/server/schema.json, app/tests/global.d.ts, app/tests/unit/lib/relay/debounceMutationMiddleware.test.ts, app/tests/unit/lib/relay/useDebouncedMutation.test.tsx, app/tests/unit/pages/create-project.test.tsx, app/yarn.lock, schema/deploy/tables/form_change.sql
Adds 
- a `useDebouncedMutation` hook
- a debounce middleware at the network layer
- a saving indicator following the UI designs
=> Add mutation debounce and Saving indicator

schema/deploy/tables/form_change.sql, schema/test/unit/tables/form_change_test.sql
=> Chore: form change trigger

app/components/Project/ProjectTableRow.tsx, app/components/Table/Table.tsx, app/components/Table/index.tsx, app/cypress/integration/cif/projects.spec.js, app/cypress/support/commands.js, app/pageRoutes.ts, app/pages/cif/projects.tsx, app/tests/unit/components/Table/index.test.tsx, app/tests/unit/pages/projects.test.tsx, schema/data/dev/002_cif_operator.sql, schema/data/dev/003_cif_project.sql, schema/data/e2e/dbReset.sql
Adds a simple table displaying the list of project, using a generic component. Pagination, filtering and ordering will be added in a subsequent PR
=> feat: add projects table

app/components/Layout/Navigation.tsx
This will ensure that the CleanBC logo renders in the first page paint
=> feat: preload CleanBC logo

app/components/Form/ProjectForm.tsx, app/components/Project/ProjectTableRow.tsx, app/lib/helpers/Money.tsx, app/lib/theme/FormWithTheme.tsx, app/lib/theme/widgets/MoneyWidget.tsx, app/package.json, app/server/schema.graphql, app/server/schema.json, app/tests/unit/components/Form/__snapshots__/ProjectForm.test.tsx.snap, app/yarn.lock, schema/deploy/tables/project.sql, schema/test/unit/tables/project_test.sql
=> Feat: show funding request amount

app/components/Form/GeneratedLongIdWidget.tsx, app/components/Form/ProjectForm.tsx, app/lib/theme/FormWithTheme.tsx, app/lib/theme/widgets/SelectParentWidget.tsx, app/schema/schema.graphql, app/schema/schema.json, app/tests/unit/components/Form/__snapshots__/ProjectForm.test.tsx.snap, schema/data/dev/002_cif_operator.sql, schema/data/dev/003_cif_project.sql, schema/deploy/tables/operator.sql, schema/deploy/tables/project.sql, schema/deploy/trigger_functions/set_project_long_id.sql, schema/revert/trigger_functions/set_project_long_id.sql, schema/sqitch.plan, schema/test/unit/tables/project_test.sql, schema/verify/trigger_functions/set_project_long_id.sql
=> Feat: generated project long id

Makefile, app/schema/schema.graphql, app/schema/schema.json, chart/cas-cif/templates/cronJobs/cron-swrs-operator-import.yaml, chart/cas-cif/templates/secret.yaml, chart/cas-cif/values-dev.yaml, chart/cas-cif/values.yaml, dags/cas_cif_dags.py, schema/data/dev/002_cif_operator.sql, schema/data/test_setup/external_database_setup.sql, schema/deploy/tables/operator.sql, schema/deploy/trigger_functions/operator_data_manually_updated.sql, schema/deploy/trigger_functions/protect_manually_updated_operator_data.sql, schema/deploy/util_functions/import_swrs_operators.sql, schema/revert/trigger_functions/operator_data_manually_updated.sql, schema/revert/trigger_functions/protect_manually_updated_operator_data.sql, schema/revert/util_functions/import_swrs_operators.sql, schema/sqitch.plan, schema/test/unit/tables/operator_test.sql, schema/test/unit/trigger_functions/operator_data_manually_updated_test.sql, schema/test/unit/trigger_functions/protect_manually_updated_operator_data_test.sql, schema/test/unit/util_functions/import_swrs_operators_test.sql, schema/verify/trigger_functions/operator_data_manually_updated.sql, schema/verify/trigger_functions/protect_manually_updated_operator_data.sql, schema/verify/util_functions/import_swrs_operators.sql
Uses postgres_fdw to import operator data from ggircs database in a separate openshift namespace
=> Feat: import operators

schema/deploy/util_functions/import_swrs_operators_from_fdw.sql, schema/test/unit/util_functions/import_swrs_operators_test.sql
I forgot form_change records followed camelCase, this really tiny fix takes care of it
=> fix: case in test and import function

app/components/Form/FormBase.tsx, app/cypress/integration/cif/project-revision/index.spec.js, app/data/jsonSchemaForm/customFormats.ts, app/data/jsonSchemaForm/projectSchema.ts, app/lib/theme/FieldTemplate.tsx, app/lib/theme/customTransformErrors.ts, app/next-env.d.ts, app/server/middleware/graphql/validateRecord.ts, app/tests/unit/components/Form/__snapshots__/FormBase.test.tsx.snap, app/tests/unit/components/Form/__snapshots__/ProjectForm.test.tsx.snap, app/tests/unit/lib/theme/__snapshots__/FormWithTheme.test.tsx.snap
colour for error messages / icon taken from:
http://web-accessibility.carnegiemuseums.org/design/color/
=> Feat: display validation errors

app/components/Form/ProjectForm.tsx, app/cypress/integration/cif/project-revision/index.spec.js, app/tests/unit/components/Form/__snapshots__/ProjectForm.test.tsx.snap
=> Feat: logically order project form fields

Makefile, chart/cas-cif/templates/networkPolicies/metabase-ingress.yaml, chart/cas-cif/values.yaml
adds a KNP to allow metabase ingress to read the cif database
=> chore: metabase knp

app/server/middleware/graphql/authenticationPgSettings.ts, schema/deploy/functions/session.sql, schema/test/unit/functions/session_test.sql
adds idir_userid to the jwt.claims & coalesces session.sub to (jwt.claims.idir_userid, jwt.claims.sub)
=> Chore: idir guid

.github/actions/local-app-run/action.yaml, .github/workflows/test.yml
PGUSER needs to be set for the entire workflow, not just install_dev_tools
=> Chore: set PGUSER for install_dev_tools

app/components/Form/ProjectManagerForm.tsx, app/mutations/Manager/deleteManagerFromRevision.ts, app/tests/unit/components/Form/ProjectManagerForm.test.tsx
uses a custom dynamic delete mutation to handle the refreshing of data.
=> Fix: refresh data on clear

app/pages/cif/operator/[operator].tsx, app/tests/unit/pages/operator/[operator].test.tsx
=> bugfix: adding bc registery id to operator view

app/mutations/Contact/createNewContactFormChange.ts, app/mutations/Operator/createEditOperatorFormChange.ts, app/mutations/Operator/createNewOperatorFormChange.ts, app/mutations/Project/createProject.ts, app/mutations/ProjectRevision/createProjectRevision.ts, app/mutations/ProjectRevision/deleteProjectRevision.ts, app/mutations/attachment/createAttachment.ts, app/mutations/useArchiveMutation.ts, app/pages/cif/contacts.tsx, app/pages/cif/project-revision/[projectRevision]/index.tsx, app/pages/cif/project/[project]/attachments.tsx, app/pages/cif/projects.tsx, app/tests/unit/components/Form/ProjectManagerFormGroup.test.tsx, app/tests/unit/mutations/useArchiveMutation.test.ts, app/tests/unit/pages/contact/[contact].test.tsx, app/tests/unit/pages/contacts.test.tsx, app/tests/unit/pages/operator/[operator].test.tsx, app/tests/unit/pages/operators.test.tsx, app/tests/unit/pages/project-revision/[projectRevision]/index.test.tsx, app/tests/unit/pages/project/[project].test.tsx, app/tests/unit/pages/projects.test.tsx
Issue: https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/309
=> Feat/error alert part 2/2

app/components/TaskList.tsx, app/tests/unit/pages/project-revision/[projectRevision]/form/contacts.test.tsx, app/tests/unit/pages/project-revision/[projectRevision]/form/managers.test.tsx, app/tests/unit/pages/project-revision/[projectRevision]/form/overview.test.tsx, app/tests/unit/pages/project-revision/[projectRevision]/index.test.tsx
Issue https://github.com/bcgov/cas-cif/issues/369
I looked at the happo diffs and they look good to me, but held off approving so the reviewer can check too
=> Feat: highlight open task in task list

app/components/TaskList.tsx, app/cypress/integration/cif/project-revision/index.spec.js, app/tests/unit/pages/project-revision/[projectRevision]/form/contacts.test.tsx, app/tests/unit/pages/project-revision/[projectRevision]/form/managers.test.tsx, app/tests/unit/pages/project-revision/[projectRevision]/form/overview.test.tsx, app/tests/unit/pages/project-revision/[projectRevision]/index.test.tsx
=> feat: showing edit project state in task list

app/components/Form/ProjectForm.tsx, app/tests/unit/components/Form/ProjectForm.test.tsx
Issue https://github.com/bcgov/cas-cif/issues/393
I'm happy with happo
=> Shorten error message about duplicate proposal reference

app/config.js
Fix PGPASSWORD not getting passed through.
=> fix: pgpassword in config

app/schema/schema.graphql, schema/deploy/computed_columns/form_change_as_project.sql, schema/deploy/computed_columns/form_change_as_project_contact.sql, schema/revert/computed_columns/form_change_as_project.sql, schema/revert/computed_columns/form_change_as_project_contact.sql, schema/sqitch.plan, schema/test/unit/computed_columns/form_change_as_project_contact_test.sql, schema/test/unit/computed_columns/form_change_as_project_test.sql, schema/verify/computed_columns/form_change_as_project.sql, schema/verify/computed_columns/form_change_as_project_contact.sql
=> Chore: as_project computed column

app/components/Form/ProjectContactForm.tsx
=> style: move submit contact button out of projectcontactform border

app/.happo.js
Card: https://github.com/bcgov/cas-cif/issues/473
If breakpoints are not enough I can add more breakpoints for each browser.
=> chore: add small screen sizes to happo

app/.eslintrc.js, app/components/Form/ProjectAnnualReportForm.tsx, app/components/Form/ProjectAnnualReportFormSummary.tsx, app/components/Form/ProjectForm.tsx, app/components/Form/ProjectManagerFormGroup.tsx, app/components/Form/ProjectMilestoneReportForm.tsx, app/components/Form/ProjectQuarterlyReportForm.tsx, app/pages/cif/project-revision/[projectRevision]/form/[formIndex]/index.tsx
Card: https://github.com/bcgov/cas-cif/issues/728
When removing something from a graphql query broke the tests or the build, I disabled eslint for the relevant lines.
=> Tech debt: set relay eslint rules to strict

app/components/Form/ProjectAnnualReportForm.tsx, app/components/Form/ProjectQuarterlyReportForm.tsx, app/components/ReportingRequirement/ReportDueIndicator.tsx, app/components/StatusBadge.tsx, app/cypress/integration/cif/project-revision/index.spec.js, app/lib/helpers/reportStatusHelpers.tsx, app/tests/unit/components/Form/ProjectAnnualReportForm.test.tsx, app/tests/unit/components/Form/ProjectQuarterlyReportForm.test.tsx, app/tests/unit/lib/helpers/reportStatusHelpers.test.ts
Card: https://github.com/bcgov/cas-cif/issues/532
Note to self: check Project Contacts Form with errors happo shots after the rebase; there were extra fields for some reason
=> Overall report status badge (quarterly and annual)

app/components/Form/ProjectAnnualReportForm.tsx, app/cypress/integration/cif/project-revision/index.spec.js, app/mutations/FormChange/undoFormChanges.ts, app/mutations/ProjectReportingRequirement/addReportingRequirementToRevision.ts.ts, app/tests/unit/components/Form/ProjectAnnualReportForm.test.tsx
Card: https://github.com/bcgov/cas-cif/issues/707
=> Undo annual report changes

app/components/Form/ProjectMilestoneReportForm.tsx, app/cypress/integration/cif/project-revision/index.spec.js, app/cypress/support/commands.js, app/mutations/FormChange/undoFormChanges.ts, app/tests/unit/components/Form/ProjectAnnualReportForm.test.tsx, app/tests/unit/components/Form/ProjectMilestoneReportForm.test.tsx
Card: https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/709
=> Undo milestone reports

app/components/Form/ProjectForm.tsx, app/cypress/integration/cif/project-revision/index.spec.js, app/cypress/support/commands.js, app/data/jsonSchemaForm/projectSchema.ts, app/schema/schema.graphql, app/tests/unit/components/Form/ProjectForm.test.tsx, schema/deploy/computed_columns/form_change_as_project.sql, schema/deploy/tables/project.sql, schema/deploy/tables/sector.sql, schema/revert/tables/sector.sql, schema/sqitch.plan, schema/test/unit/tables/project_test.sql, schema/test/unit/tables/sector_test.sql, schema/verify/tables/sector.sql
=> Feat: add project sector

app/components/Form/ProjectAnnualReportForm.tsx, app/components/Form/ProjectMilestoneReportForm.tsx, app/components/Form/ProjectQuarterlyReportForm.tsx, app/components/ReportingRequirement/Status.tsx, app/cypress/integration/cif/project-revision/index.spec.js, app/tests/unit/components/Form/ProjectAnnualReportForm.test.tsx, app/tests/unit/components/Form/ProjectMilestoneReportForm.test.tsx, app/tests/unit/components/Form/ProjectQuarterlyReportForm.test.tsx, schema/deploy/computed_columns/project_revision_upcoming_reporting_requirement_form_change.sql
Card: https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/685
=> Add status indicators to annual and milestone reports

app/lib/helpers/getTimestamptzFromDate.ts, app/lib/theme/widgets/DueDateWidget.tsx, app/lib/theme/widgets/ReceivedDateWidget.tsx, app/tests/unit/lib/theme/widgets/DueDateWidget.test.tsx
=> feat: adding clear to date pickers

app/cypress/integration/cif/project-revision/index.spec.js, app/cypress/integration/cif/projects.spec.js, app/cypress/support/commands.js, app/tests/unit/components/Form/ProjectContactForm.test.tsx, app/tests/unit/components/Form/ProjectForm.test.tsx, app/tests/unit/components/Form/ProjectManagerFormGroup.test.tsx, app/tests/unit/components/Form/ProjectQuarterlyReportForm.test.tsx, schema/data/dev/004_cif_project.sql, schema/data/dev/005_cif_reporting_requirement.sql, schema/data/dev/006_commit_project_revision.sql
Card: https://github.com/bcgov/cas-cif/issues/741
Happo diffs: The date is mocked in the `beforeEach` so there shouldn't be date-related diffs, but there are. Any suggestions?
=> Tech debt: tests for undoing changes

app/components/Form/ProjectAnnualReportForm.tsx, app/components/Form/ProjectAnnualReportFormSummary.tsx, app/components/Form/ProjectMilestoneReportForm.tsx, app/components/Form/ProjectMilestoneReportFormSummary.tsx, app/components/Form/ProjectQuarterlyReportForm.tsx, app/components/Form/ProjectQuarterlyReportFormSummary.tsx, app/cypress/support/commands.js, app/data/jsonSchemaForm/projectMilestoneSchema.ts, app/data/jsonSchemaForm/projectReportingRequirementSchema.ts, app/data/jsonSchemaForm/validationSchemas.ts, app/lib/theme/CustomDiffFields.tsx, app/lib/theme/FormWithTheme.tsx, app/lib/theme/ReadOnlyTheme.tsx, app/lib/theme/widgets/DateWidget.tsx, app/lib/theme/widgets/DueDateWidget.tsx, app/lib/theme/widgets/ReceivedDateWidget.tsx, app/tests/unit/lib/theme/widgets/DateWidget.test.tsx, app/tests/unit/lib/theme/widgets/ReceivedDateWidget.test.tsx
Zenhub: [721](https://github.com/bcgov/cas-cif/issues/721) and [748](https://github.com/bcgov/cas-cif/issues/748)
=> chore: unlink due date and received date widget

app/components/Project/ProjectMilestoneDue.tsx, app/cypress/integration/cif/project-revision/index.spec.js
Card: https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/754
=> Fix milestone status badge in project table

app/components/Form/ProjectContactForm.tsx, app/tests/unit/components/Form/ProjectContactForm.test.tsx
Card: https://github.com/bcgov/cas-cif/issues/735
Previous fix in https://github.com/bcgov/cas-cif/pull/812 didn't work
=> Bug fix: validation errors for primary contact 2

app/mutations/ProjectContact/createPrimaryContact.ts
ZH: https://github.com/bcgov/cas-cif/issues/839
=> fix: fix undoing primary contact the first time

app/cypress/integration/cif/project-revision/create-project-revision.spec.js, app/server/middleware/graphql/createFormChangeValidationPlugin.ts, app/server/middleware/graphql/index.ts, app/tests/unit/server/middleware/graphql/createFormChangeValidationPlugin.test.ts, app/tests/unit/server/middleware/graphql/formChangeValidationPlugin.test.ts
Card: https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/613
=> Fix: incorrect report tasklist status

app/components/Form/ProjectFundingAgreementForm.tsx, app/components/Form/ProjectFundingAgreementFormSummary.tsx, app/cypress/integration/cif/project-revision/index.spec.js, app/data/jsonSchemaForm/fundingAgreementSchema.ts, app/data/jsonSchemaForm/validationSchemas.ts, app/tests/unit/components/Form/ProjectFundingAgreementFormSummary.test.tsx, app/yarn.lock
issue #846
includes an update to webpack-terser-plugin, fixes CVE-2022-25858
=> Fix: display dollar sign

app/lib/helpers/getTimestamptzFromDate.ts, app/tests/unit/lib/theme/widgets/DueDateWidget.test.tsx
Card: https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/826
=> chore: prevent clearing date from throwing validation error

app/lib/theme/CustomDiffFields.tsx, app/lib/theme/ReadOnlyTheme.tsx, app/tests/unit/components/Form/ProjectMilestoneReportForm.test.tsx, app/tests/unit/components/Form/ProjectMilestoneReportFormSummary.test.tsx
=> Fix: conditional amount widget prefix

app/components/Form/ProjectFundingAgreementForm.tsx, app/cypress/integration/cif/project-revision/create-project-revision.spec.js, app/cypress/integration/cif/project-revision/index.spec.js, app/data/jsonSchemaForm/fundingAgreementSchema.ts, app/lib/theme/CustomDiffFields.tsx, app/tests/unit/components/Form/ProjectFundingAgreementForm.test.tsx
ZH: https://github.com/bcgov/cas-cif/issues/850 & https://github.com/bcgov/cas-cif/issues/849
=> Fix province holdback percentage issues

app/components/Form/ProjectAnnualReportFormSummary.tsx
ZH: https://github.com/bcgov/cas-cif/issues/810
=> fix: fix wrong annual report information on summary form

app/cypress/integration/cif/project-revision/create-project-revision.spec.js, app/cypress/integration/cif/project-revision/edit-project-revision.spec.js
removing the failing diffs, will re-add them in a subsequent PR to see if a reset fixes the issue
=> chore: reset happo diffs

app/components/Layout/DefaultLayout.tsx
ZH: https://github.com/bcgov/cas-cif/issues/449
=> fix: fix page content bouncing

app/cypress/integration/cif/project-revision/create-project-revision.spec.js, app/cypress/integration/cif/project-revision/edit-project-revision.spec.js, app/cypress/integration/cif/project-revision/undo-changes.spec.js, app/cypress/support/commands.js
ZH: https://github.com/bcgov/cas-cif/issues/907
=> chore: remove cypress wait commands

app/data/dashboardLinks/footerLinks.ts, app/tests/unit/components/Layout/Footer.test.tsx
ZH: https://github.com/bcgov/cas-cif/issues/925
=> fix: change login page link based on environment

app/tests/helpers/TestingHelper.tsx
Card: [851](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/851) 
Added better error message for `expectMutationToBeCalledWith`. It handles scenarios where the same mutation was called more than once, and none of the calls match the input variables. 
I know the `\n`s aren't pretty, but they make the error in the console much nicer.
=> chore: add more helpful error message for expectMutationToBeCalled

app/cypress/integration/cif/contacts.spec.js, app/cypress/integration/cif/operators.spec.js, app/cypress/integration/cif/project-revision/create-project-revision.spec.js, app/cypress/integration/cif/project-revision/edit-project-revision.spec.js, app/cypress/integration/cif/project-revision/index.spec.js, app/cypress/integration/cif/projects.spec.js, app/cypress/support/commands.js, schema/data/dev/005_cif_reporting_requirement.sql
ZH: https://github.com/bcgov/cas-cif/issues/929
=> fix: use mocked time to solve happo diffs

app/components/Contact/ContactDetails.tsx, app/pages/cif/contact/[contact].tsx
Card: https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/845
=> chore: wrap contact emails in a mailto

app/components/Form/ProjectContactForm.tsx, app/tests/unit/components/Form/ProjectContactForm.test.tsx
ZH: https://github.com/bcgov/cas-cif/issues/904
=> chore: debug adding and removing secondary contact form

app/data/dashboardLinks/footerLinks.ts, app/tests/unit/components/Layout/Footer.test.tsx
Card: https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/957
=> Tech debt: remove footer login

app/cypress/integration/cif/project-revision/create-project-revision.spec.js, app/cypress/integration/cif/project-revision/edit-project-revision.spec.js, app/cypress/integration/cif/project-revision/index.spec.js, app/cypress/integration/cif/project-revision/undo-changes.spec.js, app/cypress/support/commands.js, app/data/jsonSchemaForm/fundingAgreementSchema.ts, app/schema/schema.graphql, app/tests/unit/components/Form/ProjectFundingAgreementForm.test.tsx, app/tests/unit/components/Form/ProjectFundingAgreementFormSummary.test.tsx, schema/data/dev/006_cif_funding_parameter.sql, schema/deploy/tables/funding_parameter_001.sql, schema/revert/tables/funding_parameter_001.sql, schema/sqitch.plan, schema/test/unit/tables/funding_parameter_test.sql, schema/verify/tables/funding_parameter_001.sql
Card: https://github.com/bcgov/cas-cif/issues/945
Note: I changed the order of the form fields to match the wireframe
=> Add proponent cost field

app/components/Form/ProjectForm.tsx, app/schema/schema.graphql, schema/deploy/tables/project_type.sql, schema/test/unit/tables/project_type_test.sql
Additional changes re card https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/858 after PO review
=> Chore: order project types in dropdown

app/components/Form/ProjectContactForm.tsx, app/tests/unit/components/Form/ProjectContactForm.test.tsx
ZH: https://github.com/bcgov/cas-cif/issues/1042
=> fix: replace undo change mutation with discard change mutation to fix project contact issue

schema/deploy/tables/project_revision_001_add_amendment_columns.sql, schema/deploy/tables/project_revision_002.sql, schema/revert/tables/project_revision_001_add_amendment_columns.sql, schema/revert/tables/project_revision_001_add_revision_type.sql, schema/revert/tables/project_revision_002.sql, schema/sqitch.plan, schema/verify/tables/project_revision_001_add_amendment_columns.sql, schema/verify/tables/project_revision_002.sql
related migrations in the same release `project_revision_001_add_revision_type` + `project_revision_002` are combined into `project_revision_001_add_amendment_columns`
=> chore: combine related sqitch migrations into one migration file

schema/verify/tables/emission_intensity_report_001.sql, schema/verify/tables/funding_parameter_001.sql, schema/verify/tables/project_001.sql, schema/verify/tables/project_revision_001_add_amendment_columns.sql
No card associated.
based on https://github.com/bcgov/cas-cif/pull/1067#discussion_r971392409
=> refactor: correct verify files

app/cypress/integration/cif/project-revision/create-project-revision.spec.js, app/cypress/support/commands.js
[ZH Card](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/737)
=> refactor: remove cypress date picker duplicate code

app/cypress/integration/cif/project-revision/index.spec.js, app/data/formPages/formStructure.tsx
Card: https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1030
=> fix: correct budgets label

app/lib/theme/widgets/RankWidget.tsx
Card: https://github.com/bcgov/cas-cif/issues/1110
=> style: remove unnecessary dd styling in RankWidget

schema/deploy/util_functions/get_form_status.sql, schema/deploy/util_functions/get_form_status_001.sql, schema/revert/util_functions/get_form_status_001.sql, schema/sqitch.plan, schema/test/unit/util_functions/get_form_status_test.sql, schema/verify/util_functions/get_form_status_001.sql
=> chore: adding tests for get form status

app/components/TaskList/index.tsx, app/routes/pageRoutes.ts
[ZH](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1122)
=> fix: showing amendments task list only in view mode

app/cypress/integration/cif/project-revision-change-logs.spec.js
[ZH Card](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1141)
=> fix: fix project revision view page happo screenshot

app/components/TaskList/index.tsx, app/pages/cif/project-revision/[projectRevision]/create.tsx, app/pages/cif/project-revision/[projectRevision]/project-revision-change-logs.tsx, app/pages/cif/project-revision/[projectRevision]/view.tsx
[ZH Card](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1108)
=> feat: hide amendments table and view page behind the flag

app/components/Form/ProjectAnnualReportForm.tsx, app/components/Form/ProjectQuarterlyReportForm.tsx, app/components/ReportingRequirement/ReportGenerator.tsx, app/cypress/integration/cif/project-revision/create-project-revision.spec.js
[ZH Card](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1157)
- Will add e2e test once #1140 is merged.
=> chore: show date fields on report auto-generator component

app/cypress/integration/cif/project-revision/index.spec.js
https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1194
I ran happo a few times to check for flakiness and it passed every time
=> chore: happo spurious diff

app/cypress/integration/cif/project-revision/create-project-revision.spec.js, app/cypress/integration/cif/project-revision/index.spec.js, app/cypress/support/commands.js
Card: https://github.com/bcgov/cas-cif/issues/1194
=> chore: fix spurious happo diffs

app/yarn.lock
No card associated (vulnerability issue fix)
=> chore(deps): update decode-uri-component package to v0.2.1

app/schema/schema.graphql, schema/deploy/computed_columns/form_change_eligible_expenses_to_date.sql, schema/deploy/computed_columns/form_change_gross_payments_to_date.sql, schema/deploy/computed_columns/form_change_holdback_amount_to_date.sql, schema/deploy/computed_columns/form_change_net_payments_to_date.sql, schema/revert/computed_columns/form_change_eligible_expenses_to_date.sql, schema/revert/computed_columns/form_change_gross_payments_to_date.sql, schema/revert/computed_columns/form_change_holdback_amount_to_date.sql, schema/revert/computed_columns/form_change_net_payments_to_date.sql, schema/sqitch.plan, schema/test/unit/computed_columns/form_change_calculated_holdback_amount_this_milestone_test.sql, schema/test/unit/computed_columns/form_change_eligible_expenses_to_date_test.sql, schema/test/unit/computed_columns/form_change_gross_payments_to_date_test.sql, schema/test/unit/computed_columns/form_change_holdback_amount_to_date_test.sql, schema/test/unit/computed_columns/form_change_net_payments_to_date_test.sql, schema/verify/computed_columns/form_change_eligible_expenses_to_date.sql, schema/verify/computed_columns/form_change_gross_payments_to_date.sql, schema/verify/computed_columns/form_change_holdback_amount_to_date.sql, schema/verify/computed_columns/form_change_net_payments_to_date.sql
Adds computed columns for the following cumulative calculations:
- eligible_expenses
- gross_payments
- net_payments
- holdback_amount
~~This should unblock #984~~ 984 has been dropped. The functions have been reworked to be used in #717
=> Chore: cumulative milestone calculations

app/lib/theme/widgets/CalculatedValueWidget.tsx
card: https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1236
=> chore: add comma separators for money

schema/deploy/tables/project_revision_003_set_amendment_statuses.sql, schema/test/unit/tables/project_revision_003_set_amendment_statuses_test.sql
recreating a PR I accidentally closed
=> Fix: sqitch migrations

.github/actions/local-app-run/action.yaml, .github/workflows/test.yml, app/.env.example, app/components/ProjectRevision/NotifyModal.tsx, app/config.js, app/next.config.js, app/tests/unit/components/ProjectRevision/NotifyModal.test.tsx, chart/cas-cif/templates/app-deployment.yaml
ENV variables to support card: https://github.com/bcgov/cas-cif/issues/1167
=> Feat/amendment notification ENV

app/components/Form/ProjectMilestoneReportForm.tsx
[ZH Card](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1038)
=> chore: tweak milestones remove button

app/pages/unauthorized_idir.tsx, app/tests/unit/pages/unauthorized_idir.test.tsx
[ZH Card](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1172)
=> Relevant log in message

app/pages/cif/project-revision/[projectRevision]/view.tsx
Card: https://github.com/bcgov/cas-cif/issues/1167
=> chore: fix form clearing on clicking update

chart/cas-cif/templates/db-post-upgrade-job.yaml, chart/cas-cif/values-test.yaml, dags/cas_cif_dags.py
add necessary env vars
+ a quick fix for the backup-test dag
=> Chore: fix post upgrade command

README.md
add documentation about not rebasing release PRs
=> docs: update release documentation

app/mutations/ProjectRevision/updateProjectRevision.ts, app/pages/cif/project-revision/[projectRevision]/view.tsx
[ZH CARD](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1328)
=> Readonly pending actions from

chart/cas-cif/templates/postgres.yaml
missed an image in the original fix
=> fix: update pgbackrest image to use artifactory

app/components/Form/ProjectSummaryReportForm.tsx, app/components/Form/ProjectSummaryReportFormSummary.tsx, app/components/TaskList/index.tsx, app/cypress/integration/cif/project-revision/index.spec.js, app/data/formPages/formStructure.tsx, app/package.json, app/pages/cif/project-revision/[projectRevision]/form/[formIndex]/index.tsx, app/tests/unit/components/TaskList.test.tsx, app/tests/unit/pages/project-revision/[projectRevision]/form/[formIndex]/index.test.tsx
[Card](https://github.com/bcgov/cas-cif/issues/1051)
=> feat: render items in task list based on project funding stream

app/cypress/integration/cif/project-revision/create-first-project-revision.spec.js, app/cypress/support/commands.js
[Card](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1375)
=> chore: address flakiness in create first revision spec

app/components/Form/ProjectFundingAgreementFormSummary.tsx, app/components/Form/SummaryFormCommonComponents.tsx, app/tests/unit/components/Form/ProjectFundingAgreementFormSummary.test.tsx
[ZH CARD](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1043)
=> Funding agreement diff

app/components/Form/ProjectEmissionIntensityReportForm.tsx, app/components/Form/ProjectEmissionIntensityReportFormSummary.tsx, app/cypress/integration/cif/project-revision/edit-project-revision.spec.js, app/data/jsonSchemaForm/fundingAgreementSchema.ts, app/data/jsonSchemaForm/projectEmissionIntensitySchema.ts, app/lib/theme/ReadOnlyEmptyFieldTemplate.tsx, app/lib/theme/getFilteredEmissionIntensitySchema.ts
Card: https://github.com/bcgov/cas-cif/issues/1101
Note: See comment on `EmissionIntensityReportForm.tsx` re: assigning templates to UI schemas.
=> Ordering & Grouping Updates

app/cypress/integration/cif/project-revision/create-first-project-revision.spec.js, app/cypress/integration/cif/project-revision/create-subsequent-project-revision.spec.js, app/cypress/integration/cif/project-revision/discard-project-revision.spec.js, app/cypress/integration/cif/project-revision/edit-project-revision.spec.js, app/cypress/integration/cif/project-revision/index.spec.js, app/cypress/integration/cif/project-revision/undo-changes.spec.js, app/cypress/integration/cif/projects.spec.js, app/cypress/support/commands.js, schema/data/dev/004_cif_project.sql, schema/data/dev/006_cif_funding_parameter.sql
E2E tests to support #1053 and #1061
=> IA Cypress Tests

app/cypress/integration/cif/project-revision/create-first-project-revision.spec.js, app/cypress/integration/cif/project-revision/index.spec.js, app/data/jsonSchemaForm/fundingAgreementSchema.ts, app/tests/unit/components/Form/ProjectFundingAgreementForm.test.tsx, app/tests/unit/components/Form/ProjectFundingAgreementFormSummary.test.tsx
https://github.com/bcgov/cas-cif/issues/1247
=> fix: province share percentage

app/cypress/integration/cif/project-revision/create-subsequent-project-revision.spec.js, app/cypress/integration/cif/project-revision/index.spec.js
Commented out 2 screenshots and added them to the existing tech debt card #1194
=> chore: comment out flaky screenshots to be fixed later

schema/data/dev/004_cif_project.sql, schema/data/dev/006_cif_funding_parameter.sql
Card: https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1435
=> Fix IA stream dev data

app/components/Layout/ExternalLayout.tsx, app/components/Layout/Footer.tsx, app/components/Layout/Navigation.tsx, app/components/Layout/StaticLayout.tsx, app/components/Layout/SubHeader.tsx, app/data/externalLinks/footerLinks.ts, app/data/externalLinks/subHeaderLinks.ts, app/tests/unit/components/Layout/ExternalLayout.test.tsx, app/tests/unit/components/Layout/Footer.test.tsx, app/tests/unit/components/Layout/SubHeader.test.tsx
[card](https://github.com/bcgov/cas-cif/issues/1431)
=> feat: external layout component

app/components/Layout/SubHeader.tsx, app/components/Project/ProjectTableRow.tsx, app/cypress/integration/cif/operators.spec.js, app/pages/cif-external/index.tsx, app/pages/cif/projects.tsx, app/tests/unit/components/Layout/ExternalLayout.test.tsx, app/tests/unit/components/Layout/SubHeader.test.tsx, app/tests/unit/components/Project/ProjectTableRow.test.tsx, app/tests/unit/pages/cif-external/index.test.tsx, schema/data/dev/002_cif_operator.sql, schema/data/dev/004_cif_project.sql
Card: https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1412
=> External project list

app/components/Attachment/AttachmentTableRow.tsx, app/mutations/attachment/archiveAttachment.ts, app/pages/cif/project-revision/[projectRevision]/attachments.tsx, app/tests/unit/components/Attachment/AttachmentTableRow.test.tsx, app/tests/unit/pages/project/attachments.test.tsx
Card: https://github.com/bcgov/cas-cif/issues/1441
=> Delete/Archive Attachments

app/components/Form/ProjectEmissionIntensityReportForm.tsx, app/data/jsonSchemaForm/projectEmissionIntensitySchema.ts, app/lib/theme/CustomDiffFields.tsx, app/lib/theme/widgets/NumberWidget.tsx, app/lib/theme/widgets/ReadOnlyNumberWidget.tsx, app/tests/unit/components/Form/ProjectEmissionIntensityReportForm.test.tsx, app/tests/unit/components/Form/ProjectEmissionIntensityReportFormSummary.test.tsx
[ZH CARD 1437](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1437)
=> Chore zero and decimals for bei tei pei total life time

app/components/Form/ProjectFormSummary.tsx, app/components/Project/ProjectTableRow.tsx, app/components/TaskList/ExternalTaskList.tsx, app/components/TaskList/TaskListSection.tsx, app/pages/cif-external/project-revision/[projectRevision]/view.tsx, app/routes/pageRoutes.ts, app/tests/unit/pages/project-revision/[projectRevision]/form/[formIndex]/external.test.tsx, app/tests/unit/pages/project-revision/[projectRevision]/form/[formIndex]/index.test.tsx
=> feat: external project overview

app/cypress/e2e/cif/project-revision/undo-changes.cy.js
=> test: added test for undoing TEIMP agreement changes

chart/cas-cif/templates/cronJobs/cron-swrs-operator-import.yaml, chart/cas-cif/templates/cronJobs/db-init.yaml, chart/cas-cif/templates/cronJobs/deploy-data.yaml, chart/cas-cif/templates/cronJobs/deploy-database-backups.yaml, chart/cas-cif/templates/cronJobs/insert-backup-test-timestamp.yaml, chart/cas-cif/templates/cronJobs/test-database-backups.yaml
[ZH CARD](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1574)
=> chore: 1574 update cronjobs schedule

docs/README.md, docs/hotfix-strategy.md
Add documentation on the steps to apply a hotfix to production & reconcile with work in dev
=> Docs: 1269 hotfix strategy

app/cypress/support/commands.js, app/lib/theme/widgets/SelectParentWidget.tsx
[Card 1597](https://github.com/bcgov/cas-cif/issues/1597)
=> Fix: new project rfp select

app/components/ProjectRevision/ChangeReasonWidget.tsx, app/components/ProjectRevision/RevisionStatusWidget.tsx, app/cypress/e2e/cif/project-revision-change-logs.cy.js, app/cypress/e2e/cif/project-revision/create-subsequent-project-revision.cy.js, app/data/jsonSchemaForm/projectRevisionSchema.ts, app/lib/theme/ReadOnlyTheme.tsx, app/lib/theme/widgets/SelectWithNotifyWidget.tsx, app/mutations/ProjectRevision/updateProjectRevision.ts, app/mutations/ProjectRevision/useCommitProjectRevision.ts, app/pages/cif/project-revision/[projectRevision]/index.tsx, app/pages/cif/project-revision/[projectRevision]/view.tsx, app/tests/unit/components/Form/ProjectMilestoneReportForm.test.tsx, app/tests/unit/lib/theme/widgets/ChangeReasonWidget.test.tsx, app/tests/unit/lib/theme/widgets/RevisionStatusWidget.test.tsx, app/tests/unit/lib/theme/widgets/SelectWithNotifyWidget.test.tsx, schema/deploy/mutations/commit_project_revision@1.6.0.sql, schema/revert/mutations/commit_project_revision@1.6.0.sql, schema/sqitch.plan, schema/verify/mutations/commit_project_revision@1.6.0.sql
[ZH CARD](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1293)
=> 1293 Revision/Amendment committing workflow based on revision status

CHANGELOG.md, package.json, schema/sqitch.plan
To fix the issue on sqitch plan order
=> chore: release v1.7.1

app/lib/theme/widgets/SearchDropdownWidget.tsx, app/tests/unit/lib/theme/widgets/SearchDropdownWidget.test.tsx, app/tests/unit/lib/theme/widgets/__snapshots__/SearchDropdownWidget.test.tsx.snap
Card: https://github.com/bcgov/cas-cif/issues/1496
Added check for schema.anyOf in widget, now if there are no entries for the search widget, it will render "No options" like below:
=> Bug: No Contacts Error Fix

app/.happo.js
[Zenhub 1617](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1617)
=> chore: removed safari from happo

app/components/Form/SelectRfpWidget.tsx, app/lib/theme/widgets/SelectParentWidget.tsx, app/tests/unit/lib/theme/widgets/SelectParentWidget.test.tsx, app/tests/unit/lib/theme/widgets/SelectRfpWidget.test.tsx
This will fix the issue for rfp selector widget for external users. related to PR: https://github.com/bcgov/cas-cif/pull/1607
=> Fix: new project rfp select for external users

app/components/TaskList/ProjectRevisionChangeLogsTaskListSection.tsx, app/components/TaskList/TaskListItem.tsx, app/components/TaskList/index.tsx, app/cypress/e2e/cif/project-revision/create-subsequent-project-revision.cy.js, app/cypress/e2e/cif/project-revision/discard-project-revision.cy.js, app/cypress/e2e/cif/project-revision/edit-project-revision.cy.js, app/hooks/useFormIndexHelpers.tsx, app/pages/cif/project-revision/[projectRevision]/edit.tsx, app/pages/cif/project-revision/[projectRevision]/view.tsx, app/tests/unit/components/TaskList.test.tsx, app/tests/unit/pages/project-revision/[projectRevision]/form/[formIndex]/index.test.tsx
Card: https://github.com/bcgov/cas-cif/issues/1582
Note: check the card comments as well as AC as some things changed after discussion with designers
=> 1582 Preview Revision

app/routes/pageRoutes.ts, app/tests/unit/components/TaskList.test.tsx, app/tests/unit/routes/pageRoutes.test.ts
[ZH CARD 751](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/751)
=> Chore: 751 Remove deprecated anchor from tasklist

app/components/ProjectRevision/RevisionStatusWidget.tsx, app/pages/cif/project-revision/[projectRevision]/edit.tsx, app/tests/unit/lib/theme/widgets/RevisionStatusWidget.test.tsx
[ZH CARD 1676](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1676)
=> Fix: 1676 fix committing project revision

app/components/Form/ProjectForm.tsx, schema/deploy/tables/project_type_001.sql, schema/revert/tables/project_type_001.sql, schema/sqitch.plan, schema/test/unit/tables/project_type_test.sql, schema/verify/tables/project_type_001.sql
[zenhub 1421](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1421)
=> Feat: 1421 add methane capture project type

app/components/Table/Filters/SearchableDropdownFilter.tsx, app/pages/cif/projects.tsx
Card: https://github.com/bcgov/cas-cif/issues/1562
=> Primary Project Manager Table Filter Fix

app/components/TaskList/index.tsx, app/pages/cif/project-revision/[projectRevision]/create.tsx, app/pages/cif/project-revision/[projectRevision]/edit.tsx, app/pages/cif/project-revision/[projectRevision]/project-revision-change-logs.tsx, app/pages/cif/project-revision/[projectRevision]/view.tsx
Just a code clean-up, No card associated!
=> Chore: remove redundant feature flags

app/components/Dashboard.tsx, app/components/Layout/DefaultLayout.tsx, app/components/Layout/ExternalLayout.tsx, app/components/Layout/StaticLayout.tsx, app/components/StatusBadge.tsx, app/components/Table/SortableHeader.tsx, app/components/TaskList/AttachmentsTaskListSection.tsx, app/components/TaskList/ExternalTaskList.tsx, app/components/TaskList/ExternalTaskListSection.tsx, app/components/TaskList/ProjectRevisionChangeLogsTaskListSection.tsx, app/components/TaskList/TaskListItem.tsx, app/components/TaskList/index.tsx, app/lib/theme/ConfirmationAlert.tsx, app/lib/theme/colors.ts, app/lib/theme/widgets/ContextualHelp.tsx, app/lib/theme/widgets/FieldLabel.tsx, app/package.json, app/tests/unit/lib/theme/widgets/ContextualHelp.test.tsx, app/tests/unit/lib/theme/widgets/__snapshots__/ContextualHelp.test.tsx.snap, app/yarn.lock
[ZH CARD 979](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/979)
NOTE: we need to check accessibility using axe once we render the tooltip in any fields.
=> Feat: 979 reusable tooltip component

app/components/Layout/Navigation.tsx, app/tests/unit/components/Layout/DefaultLayout.test.tsx, app/tests/unit/components/Layout/Navigation.test.tsx, app/tests/unit/pages/unauthorized_idir.test.tsx
card: https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1526
=> Fix: 1526 hide nav bar when user IDIR is unauthorized

app/pages/cif/project-revision/[projectRevision]/index.tsx
card: https://github.com/bcgov/cas-cif/issues/1462, see PO review comments
=> Feat: 1462 update-make attachments visible on IA summary page

schema/deploy/functions/migration_create_project_attachment_form_changes_history.sql, schema/deploy/migrations/006-create-project-attachment-form-changes_history.sql, schema/revert/functions/migration_create_project_attachment_form_changes_history.sql, schema/revert/migrations/006-create-project-attachment-form-changes_history.sql, schema/sqitch.plan, schema/test/unit/functions/migration_create_project_attachment_form_changes_history_test.sql, schema/verify/functions/migration_create_project_attachment_form_changes_history.sql, schema/verify/migrations/006-create-project-attachment-form-changes_history.sql
[ZH CARD 1709](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1709)
=> Fix: 1709 pending attachments form changes

app/pages/cif/project-revision/[projectRevision]/edit.tsx
=> Chore: 1582 change text on discard button

app/package.json, app/yarn.lock
=> chore: fix semver package vulnerability

app/cypress/e2e/cif/project-revision-change-logs.cy.js, app/cypress/e2e/cif/project-revision/create-subsequent-project-revision.cy.js, app/cypress/e2e/cif/project-revision/discard-project-revision.cy.js, app/cypress/e2e/cif/project-revision/edit-project-revision.cy.js, app/data/jsonSchemaForm/projectRevisionSchema.ts, app/pages/cif/project-revision/[projectRevision]/edit.tsx, app/pages/cif/project-revision/[projectRevision]/view.tsx, app/tests/unit/pages/project-revision/[projectRevision]/edit.test.tsx, app/tests/unit/pages/project-revision/[projectRevision]/view.test.tsx
[ZH CARD 1663](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1663)
=> feat: 1663 remove read only revision type

app/components/Form/ProjectMilestoneReportFormSummary.tsx, app/cypress/e2e/cif/project-revision/create-first-project-revision.cy.js, app/tests/unit/components/Form/ProjectMilestoneReportFormSummary.test.tsx
=> feat: calculated milestone values diffing

schema/deploy/tables/project_type_002.sql, schema/deploy/tables/sector_001.sql, schema/revert/tables/project_type_002.sql, schema/revert/tables/sector_001.sql, schema/sqitch.plan, schema/test/unit/tables/project_type_test.sql, schema/test/unit/tables/sector_test.sql, schema/verify/tables/project_type_002.sql, schema/verify/tables/sector_001.sql
Card: https://github.com/bcgov/cas-cif/issues/1718
=> 1718 Project Overview Dropdown Updates

app/cypress/e2e/cif/project-revision/create-first-project-revision.cy.js, schema/deploy/funding_stream_project_status_001_update_hardcoded_values.sql, schema/deploy/tables/project_status_002_update_hardcoded_values.sql, schema/revert/funding_stream_project_status_001_update_hardcoded_values.sql, schema/revert/tables/project_status_002_update_hardcoded_values.sql, schema/sqitch.plan, schema/test/unit/tables/funding_stream_project_status_test.sql, schema/verify/funding_stream_project_status_001_update_hardcoded_values.sql, schema/verify/tables/project_status_002_update_hardcoded_values.sql
[zenhub 1734](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1734)
=> 1734 project status value update

app/components/Form/ProjectAnnualReportForm.tsx, app/components/Form/ProjectQuarterlyReportForm.tsx, app/components/ReportingRequirement/ReportGenerator.tsx, app/cypress/e2e/cif/project-revision/edit-project-revision.cy.js
[ZH CARD 1744](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1744)
=> Fix: 1744 show the Generate Reports button if we have an archived report

app/components/Session/SessionExpiryHandler.tsx, app/components/Session/SessionTimeoutHandler.tsx, app/tests/unit/components/Session/SessionExpiryHandler.test.tsx
[ZH CARD 1749](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1749)
=> Fix: 1749 inactivity modal issue

app/cypress/e2e/cif/project-revision/create-first-project-revision.cy.js, app/cypress/e2e/cif/project-revision/edit-project-revision.cy.js, app/cypress/e2e/cif/project-revision/index.cy.js, app/cypress/e2e/cif/project-revision/undo-changes.cy.js, app/cypress/support/commands.js, app/lib/theme/CustomDiffFields.tsx, schema/data/dev/005_cif_reporting_requirement.sql
[ZH CARD 1772](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1772)
=> chore: 1772 emissions intensity e2e tests

app/server/middleware/graphql/formChangeValidationPlugin.ts, app/tests/unit/server/middleware/graphql/formChangeValidationPlugin.test.ts
[ZH CARD 1813](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1813)
=> fix: 1813 add milestone custom mutation to validation plugin

app/components/Form/ProjectAttachmentsFormSummary.tsx, app/tests/unit/components/Form/ProjectAttachmentsFormSummary.test.tsx
[zenhub 1759](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1759)
=> fix: 1759 multiple attachment diffs issue

app/cypress/e2e/cif/project-revision/create-subsequent-project-revision.cy.js, app/data/jsonSchemaForm/projectRevisionSchema.ts, app/pages/cif/project-revision/[projectRevision]/create.tsx, app/tests/unit/pages/project-revision/[projectRevision]/create.test.tsx
https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1666
=> 1666 revision type tooltips

app/components/Form/ProjectFundingAgreementFormSummary.tsx, app/tests/unit/components/Form/ProjectFundingAgreementFormSummary.test.tsx
https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1767
=> fix: correctly handle archived funding forms

app/package.json, app/yarn.lock
fixes CVEs CVE-2023-45857 + CVE-2023-46233
=> chore: fix audit dependencies

app/package.json, app/yarn.lock
Bumping the version of next to ^14.1.1
=> chore: bump next version

app/package.json, app/yarn.lock
=> chore: update cypress

.github/actions/dev-env-setup/action.yml, .github/workflows/lint-chart.yml, .tool-versions, Makefile, chart/cas-cif/templates/hpa.yaml, requirements.txt
=> chore: update hpa k8s api version

schema/deploy/create_roles.sql
These commands never ran in a deployed cluster & block a fresh deploy
=> chore: remove grant to current user

bcgovpubcode.yml
As per DDS section meeting, we were tasked to add/update our `bcgovpubcode.yml` file in our main repos.
This PR specifically updates the versions on certain tools used along with updating the Product Owner and Data Custodian names.
=> chore/update bcgovpubcode.yml
