bcgov/cas-cif

- app/.babelrc
- app/package.json
- app/pages/_document.tsx
- app/yarn.lock
This fixes the flash of unstyled content that happens when loading the page (and is somehow more noticeable with a production build)
To replicate the issue, simply load the page with JavaScript disabled. The header, button, etc should be styled properly with the BCGov theme
> Render styles on the server for styled-components (bcgov theme components)

- app/components/Layout/Navigation.tsx
This will ensure that logged in users are redirected to the appropriate landing route
> fix: banner image should not use a `Link` to `/`

- .tool-versions
- Makefile
- chart/cas-cif/Chart.lock
- chart/cas-cif/Chart.yaml
- schema/test/unit/trigger_functions/save_form_change_test.sql
Updates the PostgreSQL server version, cas-postgres helm chart, and pgTap.
After merging this, developers will need to re-run `make install_dev_tools` in their local environment
> chore: update to postgreSQL 14

- app/package.json
- app/yarn.lock
fixes the issue described here: https://github.com/facebook/relay/issues/3649
> chore: update relay-compiler-language-typescript package

- schema/deploy/trigger_functions/deleted_records_are_immutable.sql
- schema/deploy/util_functions/upsert_timestamp_columns.sql
- schema/revert/trigger_functions/deleted_records_are_immutable.sql
- schema/sqitch.plan
- schema/test/unit/trigger_functions/deleted_records_are_immutable_test.sql
- schema/test/unit/util_functions/upsert_timestamp_columns_test.sql
- schema/verify/trigger_functions/deleted_records_are_immutable.sql
A trigger making sure that deleted records can't be updated.
It gets automatically added with the `deleted_at` column
> Feat: deleted records are immutable

- schema/deploy/tables/form_change.sql
- schema/deploy/tables/project_revision.sql
- schema/deploy/trigger_functions/commit_project_revision.sql
- schema/deploy/trigger_functions/committed_changes_are_immutable.sql
- schema/revert/trigger_functions/committed_changes_are_immutable.sql
- schema/sqitch.plan
- schema/test/unit/tables/form_change_test.sql
- schema/test/unit/tables/project_revision_test.sql
- schema/test/unit/trigger_functions/committed_changes_are_immutable_test.sql
- schema/verify/trigger_functions/committed_changes_are_immutable.sql
Making sure that committed `project_revision` and `form_change` records can't be altered
> Feat: committed changes are immutable

- .bin/pre-commit-format.sh
- .bin/pre-commit-lint.sh
- .github/ISSUE_TEMPLATE/bug-template.md
- .github/ISSUE_TEMPLATE/task-issue-template.md
- .github/ISSUE_TEMPLATE/user-story-template.md
- .pre-commit-config.yaml
- .vscode/settings.json
- COMPLIANCE.yaml
- README.md
- app/.prettierignore
- storage/README.md
- storage/docker-compose.yml
- only runs prettier and eslint on committed files (much faster pre-commit hook)
- all files are formatted by prettier (not only the ones in the `app` folder)
- only passes js/ts files to eslint, in a separate pre-commit hook as it will complain if given any other file format
> chore: only format and lint committed files

- app/components/Session/SessionExpiryHandler.tsx
- app/tests/unit/components/Session/SessionExpiryHandler.test.tsx
Small fix making sure the `SessionTimeoutHandler` component doesn't render after the session expires
> Fix: SessionTimeoutHandler doesn't render after the session expires

- chart/cas-cif/templates/cronJobs/cron-swrs-operator-import.yaml
original PR missing PG env vars for psql
> chore: add PG env vars to operator-import cronjob

- Makefile
- chart/cas-cif/templates/cronJobs/db-init.yaml
- schema/deploy/util_functions/import_swrs_operators.sql
grant usage on postgres_fdw was being done on the wrong db (postgres)
> chore: grant on cif database (not postgres)

- app/schema/schema.graphql
- app/schema/schema.json
- schema/deploy/computed_columns/project_revision_project_manager_form_changes_by_label.sql
- schema/deploy/tables/project_manager.sql
- schema/deploy/tables/project_manager_label.sql
- schema/deploy/types/manager_form_changes_by_label_composite_return.sql
- schema/revert/computed_columns/project_revision_project_manager_form_changes_by_label.sql
- schema/revert/tables/project_manager_label.sql
- schema/revert/types/manager_form_changes_by_label_composite_return.sql
- schema/sqitch.plan
- schema/test/unit/computed_columns/project_revision_project_manager_form_changes_by_label_test.sql
- schema/test/unit/functions/pending_new_project_revision_test.sql
- schema/test/unit/tables/project_manager_label_test.sql
- schema/test/unit/trigger_functions/commit_project_revision_test.sql
- schema/verify/computed_columns/project_revision_project_manager_form_changes_by_label.sql
- schema/verify/tables/project_manager_label.sql
- schema/verify/types/manager_form_changes_by_label_composite_return.sql
Adding multiple project managers will need to iterate over the # of records in the project_manager_label table and render a form whether there is form_data or not.
This computed column returns a composite return value that always contains one record for each project_manager_label and the form_data for that project and label if it exists.
Committed form_data is retrieved by latest updated (last committed).
Pending form_data takes precedence over committed form_data.
Pending form_data is only returned to the user who created it (allows concurrent editing).
This should be the majority of the database-related work required for #133
> Chore: project managers computed column

- app/schema/schema.graphql
- app/schema/schema.json
- schema/deploy/computed_columns/project_revision_project_manager_form_changes_by_label.sql
- schema/deploy/mutations/create_project.sql
- schema/deploy/types/manager_form_changes_by_label_composite_return.sql
- schema/test/unit/computed_columns/project_revision_project_manager_form_changes_by_label_test.sql
- schema/test/unit/mutations/create_project_test.sql
simplify the computed column to reflect the pattern - form changes are copied across revisions
I have temporarily hardcoded a projectManagerLabelId value in create_project() to unblock project creation. This code block will be removed in the front-end focused part of this PR since creat_project() should not create a form_change for managers by default.
> Chore: simplified managers computed column

- app/lib/pages/relayFormPageFactory.tsx
- app/pages/cif/project-revision/[projectRevision]/index.tsx
- app/tests/unit/lib/pages/relayFormPageFactory.test.tsx
- app/tests/unit/pages/project-revision/[projectRevision]/index.test.tsx
Given that committing a `form_change` record may affect many different entities, because of the use of triggers, I'm going the nuclear route here and invalidating the entire relay store. The alternative is only invalidating the records/connections that are affected, but that sounds like a lot of work to optimize this, and the scale we'll be operating at doesn't warrant this.
> fix: mark the relay store as stale when committing a form_change

- app/components/Layout/LoadingFallback.tsx
- app/components/Layout/Navigation.tsx
- app/components/Layout/StaticLayout.tsx
- app/components/Table/FilterRow.tsx
- app/components/Table/Filters/EnumFilter.tsx
- app/components/Table/Filters/TableFilter.tsx
- app/components/Table/Filters/types.tsx
- app/components/Table/Pagination.tsx
- app/components/Table/SortableHeader.tsx
- app/components/Table/index.tsx
- app/lib/relay/withRelayOptions.tsx
- app/pages/_app.tsx
- app/pages/cif/contacts.tsx
- app/pages/cif/operators.tsx
- app/pages/cif/projects.tsx
- app/tests/unit/components/Table/index.test.tsx
- Added a `LoadingFallback` for transitions between pages
- `Table` component pre-fetches the data before updating the router, following the [behaviour described in the relay docs](https://relay.dev/docs/guided-tour/refetching/refetching-queries-with-different-data/#if-you-need-to-avoid-suspense-1)
> Remove blank loading page when data is loading

- app/components/Project/ProjectTableRow.tsx
- app/pages/cif/project/[project]/index.tsx
See PO comments in https://github.com/bcgov/cas-cif/issues/337. The project manager names should show up in the same order they were entered when creating a project.
> PO review update: display project manager names in desired order

- .github/workflows/test.yml
- .gitlint
- .pre-commit-config.yaml
Issue: https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/363
Notes:
- Install the commit-msg hook to get local enforcement: `pre-commit install --hook-type commit-msg`
- I tested the github action with an unconventional commit [here](https://github.com/bcgov/cas-cif/runs/5761212800?check_suite_focus=true).
- I'm using commitlint for the github action and gitlint for local checks because that's how CIIP does it, but if we want to standardize, happy to. I'd prefer commitlint because the github action requires less config than the gitlint one, and commitlint can integrate with commitizen
> Tech debt: Enforce conventional commits

- chart/cas-cif/templates/_helpers.tpl
- chart/cas-cif/templates/app-deployment.yaml
- chart/cas-cif/templates/cronJobs/app-user.yaml
- chart/cas-cif/templates/cronJobs/cron-swrs-operator-import.yaml
- chart/cas-cif/templates/cronJobs/db-init.yaml
- chart/cas-cif/templates/cronJobs/deploy-data.yaml
- chart/cas-cif/templates/db-pre-upgrade-job.yaml
- chart/cas-cif/values.yaml
Todo: `lookup` doesn't return anything when doing a `helm template` (by design), so the helper needs to handle that to avoid throwing an exception when linting the chart
> chore: pull docker images through Artifactory

- chart/cas-cif/values-dev.yaml
- chart/cas-cif/values-prod.yaml
- chart/cas-cif/values-test.yaml
The easiest way to switch the routes in dev and test will be to uninstall and then re-install the charts
> feat: use vanity urls for the app routes

- chart/cas-cif/templates/postgres.yaml
Full backups are running at 8am, causing conflicts and jobs failing
> fix: postgres incremental backups should not run at 8am

- chart/cas-cif/values-dev.yaml
- chart/cas-cif/values-test.yaml
We're not dropping the database anymore
> fix: pre-upgrade script doesn't need to terminate connections

- app/components/Form/ProjectForm.tsx
- app/components/Form/ProjectFormSummary.tsx
- app/components/Form/ProjectManagerForm.tsx
- app/components/Form/SelectProjectStatusWidget.tsx
- app/cypress/integration/cif/project-revision/index.spec.js
- app/data/jsonSchemaForm/projectSchema.ts
- app/lib/theme/ReadOnlyFieldTemplate.tsx
- app/lib/theme/ReadOnlyTheme.tsx
- app/lib/theme/utils/getRequiredLabel.ts
- app/lib/theme/widgets/DisplayOnlyWidget.tsx
- app/lib/theme/widgets/FieldLabel.tsx
- app/lib/theme/widgets/MoneyWidget.tsx
- app/lib/theme/widgets/PhoneNumberWidget.tsx
- app/lib/theme/widgets/ReadOnlyMoneyWidget.tsx
- app/lib/theme/widgets/ReadOnlyWidget.tsx
- app/lib/theme/widgets/SearchDropdownWidget.tsx
- app/lib/theme/widgets/SelectWidget.tsx
- app/lib/theme/widgets/TextAreaWidget.tsx
- app/lib/theme/widgets/TextWidget.tsx
- app/tests/unit/components/Form/ProjectForm.test.tsx
- app/tests/unit/components/Form/__snapshots__/FormBase.test.tsx.snap
- app/tests/unit/lib/theme/widgets/__snapshots__/SearchDropdown.test.tsx.snap
- app/tests/unit/lib/theme/widgets/__snapshots__/SelectWidget.test.tsx.snap
- app/tests/unit/lib/theme/widgets/__snapshots__/TextWidget.test.tsx.snap
- app/tests/unit/pages/project-revision/[projectRevision]/index.test.tsx
- render label in rjsf fields instead of widgets
- updated summary page to display `dt` and `dd` elements on the same row
- removed operator trade name from operator selection widget
- use rjsf's `ui:help` instead of a custom option
> refactor: form label is displayed by fields, not widgets

- schema/data/dev/004_cif_project.sql
Issue https://github.com/bcgov/cas-cif/issues/499
I manually tested Gurjeet's example and also tried making my own project to confirm the bug was only happening with the dev data.
> Fix bug with total funding validation

- app/components/Table/index.tsx
- app/cypress/integration/cif/500.spec.js
- app/lib/relay/withRelayOptions.tsx
- app/package.json
- app/pages/_app.tsx
- app/yarn.lock
Issue https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/359
Notes:
- if you want to pull the branch and check it out locally, you have to build and `yarn start` If you're not in production, [you get the stack instead of the page](https://nextjs.org/docs/advanced-features/custom-error-page#:~:text=pages/_error.js%20is%20only%20used%20in%20production.%20In%20development%20you%E2%80%99ll%20get%20an%20error%20with%20the%20call%20stack%20to%20know%20where%20the%20error%20originated%20from.)
> Fix: Show custom instead of default 500 page

- app/components/Form/ProjectContactForm.tsx
- app/components/Form/ProjectContactFormSummary.tsx
- app/components/Form/ProjectManagerFormGroup.tsx
- app/components/Project/ProjectTableRow.tsx
- app/components/TaskList.tsx
- app/cypress/integration/cif/project-revision/index.spec.js
- app/hooks/useRedirectToLatestRevision.ts
- app/pages/cif/project-revision/[projectRevision]/form/contacts.tsx
- app/pages/cif/project-revision/[projectRevision]/form/managers.tsx
- app/pages/cif/project-revision/[projectRevision]/form/overview.tsx
- app/pages/cif/project-revision/[projectRevision]/index.tsx
- app/schema/schema.graphql
- app/tests/unit/pages/project-revision/[projectRevision]/form/contacts.test.tsx
- app/tests/unit/pages/project-revision/[projectRevision]/form/managers.test.tsx
- app/tests/unit/pages/project-revision/[projectRevision]/form/overview.test.tsx
- schema/deploy/computed_columns/project_latest_committed_project_revision.sql
- schema/revert/computed_columns/project_latest_committed_project_revision.sql
- schema/sqitch.plan
- schema/test/unit/computed_columns/project_latest_committed_project_revision_test.sql
- schema/verify/computed_columns/project_latest_committed_project_revision.sql
Display forms in read-only mode when viewing a committed project revision.
Includes a computed column for the latest committed project revision on a project.
Includes a hook to redirect to the latest committed project revision.
> Feat - Read-only forms

- chart/cas-cif/templates/postgres.yaml
Issue #527 
I left in the proxy and monitoring images because they seem to be required per the docs: https://access.crunchydata.com/documentation/postgres-operator/v5/references/crd/#:~:text=When%20omitted%2C%20the%20value%20comes%20from%20an%20operator%20environment%20variable.
> chore: remove default image from postgres.yaml

- Makefile
- app/server/index.ts
- chart/cas-cif/Chart.lock
- chart/cas-cif/Chart.yaml
- chart/cas-cif/templates/app-deployment.yaml
- chart/cas-cif/templates/route.yaml
- chart/cas-cif/templates/service.yaml
- chart/cas-cif/values-dev.yaml
- chart/cas-cif/values-prod.yaml
- chart/cas-cif/values-test.yaml
- chart/cas-cif/values.yaml
- dags/cas_cif_dags.py
This depends on https://github.com/BCDevOps/certbot/pull/18 being merged and the certbot Helm chart being published.
Once that's done a `helm dep up` command needs to be run to update the `Chart.lock`
> Use Certbot to manage SSL certs

- app/pages/cif/project-revision/[projectRevision]/index.tsx
- app/tests/unit/pages/project-revision/[projectRevision]/index.test.tsx
issue #234
The Discard Changes button has been moved to the top & renamed / restyled
Clicking the Discard Project Revision button replaces the button with a confirmation alert that allows you to proceed with the discard or cancel.
> Feat: discard confirmation

- cpanfile
the docker build schema job was failing, getting invalid versions of DBD::Pg and Sqitch. Updating to the latest versions fixes it
> chore: increment cpanfile version requirements

- app/components/ReportingRequirement/ReportDueIndicator.tsx
Fixing inconsistent date handling in the report due date indicator
> Fix: Due date indicator off by one day

- app/components/Project/ProjectMilestoneDue.tsx
- app/components/Project/ProjectTableRow.tsx
- app/components/StatusBadge.tsx
- app/pages/cif/projects.tsx
- app/tests/unit/components/Project/ProjectMilestoneDue.test.tsx
- app/tests/unit/components/StatusBadge.test.tsx
Adding the next due date in the project list, including a `None` indicator that was in the Figma wireframes
> Feat: Next due date in project list

- schema/data/dev/005_cif_reporting_requirement.sql
Card: https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/780
This wasn't a bug in the app. There was a typo in the dev data that made any of the pre-existing projects throw this error.
> Bug: Cannot add Milestone to project with existing Milestone

- shipit.yml
Now that we have a top-level package.json, shipit tried installing packages with yarn
> chore: override shipit dependency steps

- app/pages/cif/projects.tsx
Issue #744
Removing the ability to sort managers. The sort was causing an error and there is no use in sorting this column as each row contains a list of users.
> fix: remove sorting for project managers from project list

- app/components/Form/ProjectForm.tsx
Card: https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/870
Only show bcRegistryId if it exists for legal operators.
> chore: don't show null bc registry ids

- app/lib/theme/widgets/AdjustableCalculatedValueWidget.tsx
- app/tests/unit/lib/theme/widgets/AdjustableCalculatedValueWidget.test.tsx
Card: https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/971
Previously the `AdjustableCalculatedValueWidget` set empty values to `null` which caused validation errors on an empty field after clearing it. Setting it to `undefined` in those cases fixes this.
> chore: fix AdjustableCalculatedValueWidget validation errors

- app/components/Form/ProjectEmissionIntensityReportForm.tsx
- app/components/Form/ProjectEmissionIntensityReportFormSummary.tsx
- app/cypress/integration/cif/project-revision/create-project-revision.spec.js
- app/data/jsonSchemaForm/projectEmissionIntensitySchema.ts
- app/lib/theme/widgets/ReadOnlyCalculatedValueWidget.tsx
- app/tests/unit/components/Form/ProjectEmissionIntensityReportForm.test.tsx
- app/tests/unit/components/Form/ProjectEmissionIntensityReportFormSummary.test.tsx
- app/tests/unit/lib/theme/widgets/ReadOnlyCalculatedValueWidget.test.tsx
This was preventing us from using multiple `ReadonlyCalculatedWidget` widgets on one form
> refactor: ReadonlyCalculatedWidget can be configured for any value from form context

- app/components/TaskList/index.tsx
- app/cypress/integration/cif/project-revision/index.spec.js
Card: https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/972
A couple notes:
- this PR separates the quarterly report and TEIMP statuses, but there's still a bug with the TEIMP status captured in [this card](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/970)
- the regression test is the happo screenshot with the separated statuses
> Fix: separate quarterly and teimp statuses

- schema/data/dev/002_cif_operator.sql
- schema/data/dev/007_commit_project_revision.sql
- schema/deploy/util_functions/verify_function_not_present.sql
- schema/deploy/util_functions/verify_function_not_present@1.0.0-rc.4.sql
- schema/revert/computed_columns/form_change_as_emission_intensity_report.sql
- schema/revert/computed_columns/form_change_as_project.sql
- schema/revert/computed_columns/project_revision_teimp_payment_amount.sql
- schema/revert/tables/emission_intensity_report_001.sql
- schema/revert/tables/project_001.sql
- schema/revert/util_functions/verify_function_not_present@1.0.0-rc.4.sql
- schema/sqitch.plan
- schema/test/unit/util_functions/verify_function_not_present_test.sql
- schema/verify/trigger_functions/commit_form_change.sql
- schema/verify/trigger_functions/commit_project_revision.sql
- schema/verify/util_functions/verify_function_not_present.sql
- schema/verify/util_functions/verify_function_not_present@1.0.0-rc.4.sql
- change verify_function_not_present utility function to include schema and number of input parameters in the check
- fix broken revert logic
- add missing verify checks for deleted trigger functions `commit_form_change` and `commit_project_revision`
- fix dev data so it doesn't output unncessary lines to the console
> Chore: verify function not present with schema

- app/cypress/integration/cif/project-revision/create-project-revision.spec.js
The create-project-revision test always fails locally for me. This fixes it.
> Test: fix bug that makes create-project-revision fail locally

- app/components/TaskList/ProjectRevisionChangeLogsTaskListSection.tsx
[ZH Card](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1142)
> fix: remove caret from project revision tasklist when has no child

- app/cypress/integration/cif/contacts.spec.js
- app/data/jsonSchemaForm/contactSchema.ts
- app/data/jsonSchemaForm/customFormats.ts
- app/lib/theme/customTransformErrors.ts
- app/server/middleware/graphql/validateRecord.ts
- Added regex for phone number and email addresses, with custom validation error messages.
- Enforced the patterns on their respective fields in the `contractSchema`
> Feat: contact phone and email validation

- dags/cas_cif_dags.py
The test restore job hangs from 2-4 am every day and then runs at 4, Experimenting running this just after 4am to see if this has an effect on the long restore time.
> chore: run dag at 4:15 am local

- chart/cas-cif/templates/cronJobs/test-database-backups.yaml
> chore: move env vars into init container, use bin/bash

- app/package.json
- app/yarn.lock
No Card
updates
jsonwebtoken package version to 9.0.0
json5 to version 2.2.2
which contains the vulnerability patch based on notification from `yarn audit` 
[jsonwebtoken](https://github.com/advisories/GHSA-27h2-hvpr-p74q)
[json5](https://github.com/advisories/GHSA-9c47-m6qq-7p4h)
> chore: update jsonwebtoken version to fix vulnerability

- .github/workflows/codeql-analysis.yml
Card: https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1215
Codeql v1 actions are set to be deprecated at the same time as GHES 3.3, which is currently scheduled for January 2023.
Bumping the actions to v2 as per https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/
> chore: update codeql actions to use v2 as v1 is being deprecated

- chart/cas-cif/templates/cronJobs/test-database-backups.yaml
- chart/cas-cif/templates/postgres.yaml
- database_backup_test/backup-test/templates/postgres.yaml
Use images in artifactory for the Postgres Operator, fixes an image-pull error when using the crunchy hosted images
plus a couple of tweaks to the db backup tests
> Chore: pgo artifactory images

- chart/cas-cif/templates/postgres.yaml
missed one image for the monitoring exporter
> chore: use artifactory image for crunchy monitoring exporter

- chart/cas-cif/templates/cronJobs/test-database-backups.yaml
- database_backup_test/backup-test/templates/postgres.yaml
had an unnecessary directory in the command that was causing noise in the output
> Chore: remove directory from uninstall command

- app/components/Form/ProjectEmissionIntensityReportForm.tsx
- app/tests/unit/components/Form/ProjectEmissionIntensityReportForm.test.tsx
Card: https://github.com/bcgov/cas-cif/issues/1442
I'm not sure why there's a happo diff on [IA Project funding agreement Form](https://happo.io/a/336/p/1010/compare/1d1c42e0bea21c11e4cd2f095751cef26df30f22/bf860fad2146ec1d35140d99f8a70f2320a7d64e?t=diffs&target=chrome-laptop#IA%5C%20Project%5C%20funding%5C%20agreement%5C%20Form). However, the "Total Project Payment Amount to Date" calculation isn't completed yet ([card to finish it here](https://github.com/bcgov/cas-cif/issues/1442)), so probably not worth worrying about diffs at this stage since either placeholder is acceptable at this point.
> Fix actual performance milestone calculation

- chart/cas-cif/templates/backup-test-secret.yaml
- chart/cas-cif/templates/cronJobs/test-database-backups.yaml
This cronjob was relying on a secret that was created manually in openshift. Removing that dependency and using an helm-created secret.
> chore: remove need for manually created secret

- docs/developer-guide.md
No Card
A very small update to the developer guide for running e2e tests in headless mode
> Update e2e testing in dev docs

- yarn.lock
update vm2 dependency of release-it to unaffected version.
> chore: fix CVE-2023-29017

- app/components/ProjectRevision/ProjectRevisionTableRow.tsx
- app/components/ProjectRevision/RevisionRecordHistory.tsx
- app/components/ProjectRevision/RevisionStatusWidget.tsx
- app/cypress/e2e/cif/project-revision-change-logs.cy.js
- app/cypress/e2e/cif/project-revision/create-subsequent-project-revision.cy.js
- app/cypress/e2e/cif/project-revision/discard-project-revision.cy.js
- app/cypress/e2e/cif/project-revision/edit-project-revision.cy.js
- app/cypress/e2e/cif/project-revision/undo-changes.cy.js
- app/cypress/support/commands.js
- app/hooks/useRedirectToValidFormIndex.ts
- app/pages/cif/project-revision/[projectRevision]/edit.tsx
- app/pages/cif/project-revision/[projectRevision]/form/[formIndex]/index.tsx
- app/routes/pageRoutes.ts
- app/tests/unit/components/ProjectRevision/RevisionRecordHistory.test.tsx
- app/tests/unit/lib/theme/widgets/RevisionStatusWidget.test.tsx
- app/tests/unit/pages/project-revision/[projectRevision]/edit.test.tsx
- app/tests/unit/pages/project-revision/[projectRevision]/view.test.tsx
card: https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1561
Note: I decided to do this a little differently from the dev checklist. Instead of using a tasklist mode, I made separate edit and view pages. We've all been confused about this new workflow and where the code lives, and I think separate pages makes it clearer (it's also more consistent with the rest of forms, which have separate form and summary components).
> Feat: 1561 Editing workflow

- app/components/Form/ProjectEmissionIntensityReportFormSummary.tsx
Addressing a bug (reported in Teams) -> "Missing" Emissions info
[ZH CARD 1647](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1647)
> fix: show emission intensity data on view mode

- app/components/Project/ProjectMilestoneDue.tsx
Addressing a bug (reported  in Teams) where completed milestones were showing up as late in the projects table under 'Milestone Due' column.
> chore: change sort order of report due date

- app/lib/theme/CustomDiffFields.tsx
Card: https://github.com/bcgov/cas-cif/issues/1231
This PR is to address the comment in the card about REMOVED not showing up properly in rank diffs
> Chore: 1231 tweak--show removed text for calculated diffs

- app/components/Form/ApplicationOverviewForm.tsx
- app/tests/unit/components/Form/ApplicationOverviewForm.test.tsx
[ZH CARD 1651](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1651)
> Fix: 1651 not using hardcoded rfp ID

- schema/deploy/computed_columns/project_revision_total_project_value.sql
- schema/deploy/functions/handle_funding_parameter_form_change_commit.sql
- schema/test/unit/functions/handle_funding_parameter_form_change_commit_test.sql
There were some functions that were incorrectly casting numeric values to integers, which was preventing users from submitting funded projects along with some other unintended behaviour.
> Hotfix: fix incorrect integer casts

- app/components/Form/ProjectForm.tsx
[ZH CARD 805](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/805)
Note: Operator ID had the same issue which is not mentioned in the card itself but got fixed in this PR.
> fix: showing `not added` when project status and operator not filled out

- app/components/Form/FormBase.tsx
- app/components/Form/SummaryFormCommonComponents.tsx
- app/cypress/e2e/cif/project-revision/create-subsequent-project-revision.cy.js
- app/cypress/e2e/cif/project-revision/edit-project-revision.cy.js
- app/lib/theme/CustomDiffFields.tsx
- app/pages/cif/project-revision/[projectRevision]/view.tsx
- app/tests/unit/components/Form/ProjectAnnualReportFormSummary.test.tsx
- app/tests/unit/components/Form/ProjectContactFormSummary.test.tsx
- app/tests/unit/components/Form/ProjectEmissionIntensityReportFormSummary.test.tsx
- app/tests/unit/components/Form/ProjectFundingAgreementFormSummary.test.tsx
- app/tests/unit/components/Form/ProjectMilestoneReportFormSummary.test.tsx
- app/tests/unit/components/Form/ProjectQuarterlyReportFormSummary.test.tsx
- app/tests/unit/components/Form/__snapshots__/FormBase.test.tsx.snap
- app/tests/unit/components/ProjectRevision/CollapsibleFormWidget.test.tsx
- app/tests/unit/lib/theme/CustomDiffFields.test.tsx
#1569 
- this refactor uses a stack implementation
- explicitly checks for undefined/null
- decimal values check added (note: some decimal values still seem incorrect from the different forms: tiemp)
- zero's are tested comprehensively
> refactor: custom diff fields

- app/components/Layout/Navigation.tsx
- app/components/Session/LoginForm.tsx
- app/pages/index.tsx
- app/tests/unit/components/Layout/ExternalLayout.test.tsx
- app/tests/unit/components/Layout/Navigation.test.tsx
- app/tests/unit/pages/login-redirect.test.tsx
[zenhub 1644](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1644)
> 1644 login redirect functionality

- app/data/jsonSchemaForm/emissionIntensityUiSchema.ts
- app/data/jsonSchemaForm/fundingParameterEPUiSchema.ts
- app/data/jsonSchemaForm/fundingParameterIAUiSchema.ts
- app/data/jsonSchemaForm/projectEmissionIntensitySchema.ts
- app/data/jsonSchemaForm/projectMilestoneUiSchema.ts
- app/data/jsonSchemaForm/tooltipText.ts
- app/lib/theme/widgets/AdjustableCalculatedValueWidget.tsx
- app/lib/theme/widgets/ContextualHelp.tsx
- app/tests/unit/components/Form/ProjectEmissionIntensityReportForm.test.tsx
- app/tests/unit/components/Form/ProjectEmissionIntensityReportFormSummary.test.tsx
- app/tests/unit/components/Form/ProjectFundingAgreementForm.test.tsx
- app/tests/unit/components/Form/ProjectFundingAgreementFormSummary.test.tsx
- app/tests/unit/components/Form/ProjectMilestoneReportForm.test.tsx
- app/tests/unit/components/Form/ProjectMilestoneReportFormSummary.test.tsx
- app/tests/unit/components/Form/__snapshots__/ProjectEmissionIntensityReportFormSummary.test.tsx.snap
- app/tests/unit/components/Form/__snapshots__/ProjectFundingAgreementFormSummary.test.tsx.snap
- app/tests/unit/components/Form/__snapshots__/ProjectMilestoneReportFormSummary.test.tsx.snap
- app/tests/unit/lib/theme/widgets/AdjustableCalculatedValueWidget.test.tsx
- app/tests/unit/lib/theme/widgets/ContextualHelp.test.tsx
- app/tests/unit/lib/theme/widgets/__snapshots__/ContextualHelp.test.tsx.snap
card #1692 
continued from https://github.com/bcgov/cas-cif/pull/1771/files
> Feat: 1692 tooltips

- database_backup_test/backup-test/templates/postgres.yaml
[ZH CARD 1707](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1707)
> Fix: 1707 change obsolete images for PGO in backup test chart

- app/components/Form/ProjectContactFormSummary.tsx
- app/tests/unit/components/Form/ProjectContactFormSummary.test.tsx
[ZH CARD 1808](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1808)
> Fix: 1808 shows secondary contacts in project contact summary form

- app/components/Form/ProjectEmissionIntensityReportFormSummary.tsx
- app/components/Form/ProjectFundingAgreementFormSummary.tsx
- app/lib/theme/schemaFilteringHelpers.ts
- app/package.json
- app/pages/cif/project-revision/[projectRevision]/edit.tsx
- app/pages/cif/project-revision/[projectRevision]/form/[formIndex]/index.tsx
- app/pages/cif/project-revision/[projectRevision]/index.tsx
- app/pages/cif/project-revision/[projectRevision]/view.tsx
- app/tests/unit/components/Form/ProjectEmissionIntensityReportFormSummary.test.tsx
card: https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1788
Note: Anticipated Funding Per Fiscal Year is no longer in the happo shot. That's correct--the cypress test doesn't change anything that would create a diff in anticipated funding.
> fix: 1788 show budgets diffs triggered by milestone changes

- chart/cas-cif/templates/terraform/terraform-apply.yaml
When deploying #1887, Terraform initializes in the job's pod, but fails on line 58 due to `/bin/sh: syntax error: unterminated quoted string`, a hanging `"`. This fix removes the erroneous quote mark.
> fix: remove hanging quote

- .github/workflows/test.yml
The image being used for Zaproxy can't be found anymore so we've changed the image source and bumped the action version.
> chore: update zaproxy action version and image source

- chart/cas-cif/templates/postgres.yaml
- database_backup_test/backup-test/templates/postgres.yaml
We have had our crunchy versions pinned. From the [docs](https://github.com/bcgov/crunchy-postgres/blob/main/charts/crunchy-postgres/values.yaml#L3): `it's not necessary to specify an image as the images specified in the Crunchy Postgres Operator will be pulled by default`.
> chore: use the default crunchy image instead of a pinned version

- app/cypress/e2e/cif/project-revision/create-first-project-revision.cy.js
- app/cypress/e2e/cif/project-revision/undo-changes.cy.js
- schema/deploy/tables/funding_stream_rfp_002.sql
- schema/revert/tables/funding_stream_rfp_002.sql
- schema/sqitch.plan
- schema/test/unit/tables/funding_stream_rfp_test.sql
- schema/verify/tables/funding_stream_rfp_002.sql
card: https://github.com/bcgov/cas-cif/issues/1917#issuecomment-2135841962
This PR:
- add 2024 via sqitch
- changes the e2e test for creating a project to use 2024 instead of 2020
> Add 2024 to the funding stream rfp table
